# Generated by Django 4.1.6 on 2023-02-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=120)),
                ('Last_Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.TimeField(max_length=50)),
                ('Message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
