# Generated by Django 4.1.6 on 2023-02-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='First_Name',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Last_Name',
            new_name='lName',
        ),
    ]
