# Generated by Django 4.1.6 on 2023-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_first_name_contact_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(default='Write your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(default='Write ur message'),
        ),
    ]
