# Generated by Django 4.1.6 on 2023-02-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lName',
            new_name='Last_Name',
        ),
    ]
